### ISSUE TITLE
Error Fichier inexistant

### ISSUE THREAD

**Issue by 73k05** [73k05/fonkybats-front#3]
Salut @adrienND ,

le fichier `../_media_queries.css` n'existe pas dans le repo, peut-on supprimer l'import? Si possible essayer de vérifier les erreurs de la console lors du dernier push 🙂 Dans `footer.css` et `about.css`

https://github.com/73k05/fonkybats-front/blob/646994be7fa8f3fc96844440522c5fa228d5e2b0/stylesheets/components/_footer.css#L5

J'ai aussi une autre erreur sur flickity 
```
flickity.js:1 Uncaught TypeError: $(...).flickity is not a function
    at flickity.js:1
(anonymous) @ flickity.js:1
```

**Comment by 73k05** [comment]
Autre chose que je ne comprends pas c'est `loading.html` c'est quoi?

**Comment by adrienND** [comment]
@73k05 Yo

**1. Erreur avec les media queries**
Oui oui pour `@import "../_media_queries.css"; `
c'est une erreur de ma part, il faut bien y supprimer

**2. Erreur flickity**
Je viens de voir qu'il y a bien les liens cdn pour jquery et flickity bizarre.
En tout cas je viens de pull la branch main et je n'ai pas cette erreur de mon côté et flickity fonctionne bien

**3. Page loading.html**
C'est la page qui correspond au site avant le pre-sale avec le compte à rebours et sans la connection au wallet. La page `index.html` contient les bouton pour se connecter au wallet. Si tu veux voir la différence ouvre les dans le navigateurs

**Comment by 73k05** [comment]
> Autre chose que je ne comprends pas c'est `loading.html` c'est quoi?

Oublie ça j'ai compris et merge les deux fichiers en un seul.

**Comment by 73k05** [comment]
Salut,
 
> **1. Erreur avec les media queries** Oui oui pour `@import "../_media_queries.css"; ` c'est une erreur de ma part, il faut bien y supprimer

Done 👍🏽

> **2. Erreur flickity** Je viens de voir qu'il y a bien les liens cdn pour jquery et flickity bizarre. En tout cas je viens de pull la branch main et je n'ai pas cette erreur de mon côté et flickity fonctionne bien

Oui c'est bizarre, si tu as un moment pour regarder le `main` ce serait cool sinon je regarderai plus tard. C'est primordial?

> **3. Page loading.html** C'est la page qui correspond au site avant le pre-sale avec le compte à rebours et sans la connection au wallet. La page `index.html` contient les bouton pour se connecter au wallet. Si tu veux voir la différence ouvre les dans le navigateurs

Ok j'ai merge les deux et ajouté des css hide plutot.

Merci pour le support!
Adios

**Comment by 73k05** [comment]
@adrienND J'ai ajouté un champ input `nftAdMintAddress` pour que Freddy puisse mint avant tout le monde des NFT et les envoyer a une adresse directement, par contre j'arrive pas a afficher correctement le contour gradient que tu as sur les boutons, si tu peux me le faire vite euf 🙏🏽

Ci-joint le screenshot, faut que tu enlève les hide pour l'afficher, on voit que c'est en bleu quand je clique dessus mais sinon c'est invisible...
<img width="848" alt="Screenshot 2021-11-17 at 17 34 12" src="https://user-images.githubusercontent.com/9129812/142241944-e218bab7-ee6e-4234-a6d1-6ecd7d72a214.png">
<img width="860" alt="Screenshot 2021-11-17 at 17 32 53" src="https://user-images.githubusercontent.com/9129812/142241702-cf13eca0-bb34-4a93-a801-dcdfe72a0bc6.png">

**Comment by adrienND** [comment]
@73k05 ajout du style envoyé sur la branch main pour l'input

**Comment by 73k05** [comment]
Super, bravo!

Pour info, le bouton `Connect Wallet` est toujours dispo car cela conditionne la partie admin pour Freddy afin de

- Changer l'état de la sale
- AdMinter des NFTs pour distribuer a droite a gauche
