### ISSUE TITLE
Missing UI component

### ISSUE THREAD

**Issue by 73k05** [73k05/fonkybats-front#4]
@adrienND ,

il me semble qu'il manque des composants:

- Popup/Message de retour de contrat avec le mint OK/KO
- Prix du NFT en temps réel 0.07Ξ -> 0.09Ξ
- ...

**Comment by adrienND** [comment]
@73k05

**1.Popup/Message de retour de contrat avec le mint OK/KO**
Une popup qui s'affiche après que la personne à bien validé son Mint ou une erreur ? quel texte doit apparaitre dans cette popup ?

**2. Prix du NFT en temps réel 0.07Ξ -> 0.09Ξ**
Je ne vois pas trop ou il faut le mettre dans le header ? Il y a déjà l'information présente dans la partie roadmap

**Comment by 73k05** [comment]
> **1.Popup/Message de retour de contrat avec le mint OK/KO** Une popup qui s'affiche après que la personne à bien validé son Mint ou une erreur ? quel texte doit apparaitre dans cette popup ?

Je verrais bien les deux 

- `Good Job, you've successfully Minted 5 Fonky Bats NFTs, trade them now on OpenSea...`
- `Mint Error, please check your MetaMask connection`

> **2. Prix du NFT en temps réel 0.07Ξ -> 0.09Ξ** Je ne vois pas trop ou il faut le mettre dans le header ? Il y a déjà l'information présente dans la partie roadmap

Oui mais c'est pas suffisant, entre le slide et le bouton? Avec le prix d'un NFT et le montant total. Faudra peut-être réduire les margins button pour que ça passe? On peut mettre les infos en petit.
<img width="625" alt="Screenshot 2021-11-18 at 11 25 13" src="https://user-images.githubusercontent.com/9129812/142398127-37f9e876-04a6-4082-a4f4-d979760dbed9.png">

**Comment by adrienND** [comment]
@73k05 je viens de faire plusieurs push sur main : 

- ajout du prix par nft (à modifié selon l'étape de vente "pre-sale" ou "main sales"

- ajout du component popup : 
j'ai mis un trigger sur le logo du header pour ouvrir la popup afin que tu aies un exemple.
De plus, dans la popup tu trouveras le text pour le "success" et "fail" qui faudra afficher selon les cas.

- fix sur les liens des media sociaux

**Comment by 73k05** [comment]
Good Job 👏
